apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-04-30T09:15:50Z"
    generation: 1
    labels:
      name: elasticsearch-operator
      pod-template-hash: 6448ccf74
    name: elasticsearch-operator-6448ccf74
    namespace: openshift-operators-redhat
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: elasticsearch-operator
      uid: 2f5fb699-8ac3-11ea-a13f-00505691b701
    resourceVersion: "666487"
    selfLink: /apis/extensions/v1beta1/namespaces/openshift-operators-redhat/replicasets/elasticsearch-operator-6448ccf74
    uid: 2f60ae93-8ac3-11ea-a13f-00505691b701
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: elasticsearch-operator
        pod-template-hash: 6448ccf74
    template:
      metadata:
        annotations:
          alm-examples: |-
            [
                {
                    "apiVersion": "logging.openshift.io/v1",
                    "kind": "Elasticsearch",
                    "metadata": {
                      "name": "elasticsearch"
                    },
                    "spec": {
                      "managementState": "Managed",
                      "nodeSpec": {
                        "image": "registry.redhat.io/openshift4/ose-logging-elasticsearch5@sha256:e4cca1134b7213c8877ac6522fcad172e0f47eea799020eed25b90dc928af28e",
                        "resources": {
                          "limits": {
                            "memory": "1Gi"
                          },
                          "requests": {
                            "memory": "512Mi"
                          }
                        }
                      },
                      "redundancyPolicy": "SingleRedundancy",
                      "nodes": [
                        {
                            "nodeCount": 1,
                            "roles": ["client","data","master"]
                        }
                      ]
                    }
                }
            ]
          capabilities: Seamless Upgrades
          categories: OpenShift Optional, Logging & Tracing
          certified: "false"
          containerImage: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:06cc3bb287740360e4c0071dab8ea4254baa02a67205424241cfbfe8b2b8f375
          createdAt: "2019-02-20T08:00:00Z"
          description: |-
            The Elasticsearch Operator for OKD provides a means for configuring and managing an Elasticsearch cluster for tracing and cluster logging.
            ## Prerequisites and Requirements
            ### Elasticsearch Operator Namespace
            The Elasticsearch Operator must be deployed to the global operator group namespace
            ### Memory Considerations
            Elasticsearch is a memory intensive application.  The initial
            set of OKD nodes may not be large enough to support the Elasticsearch cluster.  Additional OKD nodes must be added
            to the OKD cluster if you desire to run with the recommended (or better) memory. Each ES node can operate with a
            lower memory setting though this is not recommended for production deployments.
          olm.operatorGroup: openshift-operators-redhat
          olm.operatorNamespace: openshift-operators-redhat
          olm.skipRange: '>=4.1.0 <4.2.29-202004140532'
          olm.targetNamespaces: ""
          support: AOS Cluster Logging, Jaeger
        creationTimestamp: null
        labels:
          name: elasticsearch-operator
          pod-template-hash: 6448ccf74
      spec:
        containers:
        - command:
          - elasticsearch-operator
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: elasticsearch-operator
          - name: PROXY_IMAGE
            value: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:dc0fcd9252214037a45f15bdfdd703f47fd95e8f98895552bb6e7b2d205081c5
          - name: ELASTICSEARCH_IMAGE
            value: registry.redhat.io/openshift4/ose-logging-elasticsearch5@sha256:e4cca1134b7213c8877ac6522fcad172e0f47eea799020eed25b90dc928af28e
          image: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:06cc3bb287740360e4c0071dab8ea4254baa02a67205424241cfbfe8b2b8f375
          imagePullPolicy: IfNotPresent
          name: elasticsearch-operator
          ports:
          - containerPort: 60000
            name: metrics
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: elasticsearch-operator
        serviceAccountName: elasticsearch-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
