apiVersion: v1
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    grafana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoSchedule"
      - key: "infra"
        operator: "Equal"
        value: "reserved"
        effect: "NoExecute"
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
