apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app: argocd-operator
resources:
- argocd-namespace.yaml
- argocd-operatorgroup.yaml
- argocd-subscription.yaml
vars:
- name: ARGOCD_PROJECT_NAME
  objref:
    kind: Namespace
    name: argocd
    apiVersion: v1
