apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Project to run Cluster Logging and ElasticSearch Operators
    openshift.io/node-selector: ""
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Equal","key":"infra","value":"reserved"}]'
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-operators-redhat
spec:
  finalizers:
  - kubernetes
