global:
  resolve_timeout: 5m
  smtp_from: "admin@example.com"
  smtp_smarthost: "smtp.mailtrap.io:2525"
  smtp_auth_username: "b7b84fc3e5d118"
  smtp_auth_password: "445836087a81f3"
  smtp_require_tls: false
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: email
  routes:
  - match:
      alertname: Watchdog
    repeat_interval: 5m
    receiver: email
  - match:
      severity: critical
    repeat_interval: 5m
    receiver: email
receivers:
- name: default
- name: nagios
  webhook_configs:
  - url: 'http://nagios.example.com:8000/'
- name: email
  email_configs:
    - to: "rahmed@redhat.com"
      # TLS configuration.
      tls_config:
        insecure_skip_verify: True
